# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: cifar10.yaml
  - model: cifar10.yaml
  - paths: default.yaml
  - trainer: default.yaml

# task name, determines output directory path
task_name: "eval"


# simply provide checkpoint path to resume training
ckpt_path: ${paths.root_dir}/model_checkpoint/model.ckpt

